### ISSUE TITLE
scene-tester logs errors and warnings

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#187]
Trying Rend3 0.1.0. Scene appears, but there are errors and warnings at startup indicating that initialization had problems.

```
RUST_LOG=warn ./scene-viewer
[WARN  wgpu_hal::vulkan::instance] Unable to find layer: VK_LAYER_KHRONOS_validation
[WARN  wgpu_hal::gles::egl] No config found!
[WARN  wgpu_core::device] Surface does not support present mode: Mailbox, falling back to FIFO
[ERROR wgpu_core::validation] Unexpected varying type: Array { base: [4], size: Constant([8]), stride: 4 }
[ERROR wgpu_core::validation] Unexpected varying type: Array { base: [4], size: Constant([5]), stride: 4 }
Reading gltf file: /home/john/projects/rend3/examples/scene-viewer/data/scene.gltf
basisu_transcoder::basisu_transcoder_init: Initializing (this is not an error)
[WARN  wgpu_core::device] Surface does not support present mode: Mailbox, falling back to FIFO
```

**Comment by John-Nagle** [comment]
Possibly-related crash running my slscenetester, which worked on the old Rend3.  This uses the setup code from scene-tester, but loads much other content.

```
./slscenetester --dumpfile ../../../testdata/boardroom.json
Logging to "/tmp/log.txt"
02:56:21 [WARN] Unable to find layer: VK_LAYER_KHRONOS_validation
02:56:21 [WARN] No config found!
02:56:21 [WARN] Surface does not support present mode: Mailbox, falling back to FIFO
02:56:21 [ERROR] Unexpected varying type: Array { base: [4], size: Constant([8]), stride: 4 }
02:56:21 [ERROR] Unexpected varying type: Array { base: [4], size: Constant([5]), stride: 4 }
basisu_transcoder::basisu_transcoder_init: Initializing (this is not an error)
Reading gltf file: /home/john/projects/sl/SL-test-viewer/slscenetester/data/unitcube2.gltf
Region offset for "Boardroom": [0, 0, 0]
02:56:23 [WARN] Surface does not support present mode: Mailbox, falling back to FIFO
thread 'main' panicked at 'range end index 39146836 out of range for slice of length 33554592', /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/util/device.rs:128:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::slice::index::slice_end_index_len_fail
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/slice/index.rs:41:5
   3: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/slice/index.rs:240:13
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/slice/index.rs:15:9
   5: <wgpu::Device as wgpu::util::device::DeviceExt>::create_texture_with_data
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/util/device.rs:128:22
   6: rend3::renderer::render::render_loop
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/rend3-0.1.0/src/renderer/render.rs:200:40
   7: rend3::renderer::Renderer::render
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/rend3-0.1.0/src/renderer/mod.rs:219:9
   8: slscenetester::displaystate::{{closure}}
             at /home/john/projects/sl/SL-test-viewer/slscenetester/src/main.rs:694:40
   9: winit::platform_impl::platform::sticky_exit_callback
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:746:5
  10: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/x11/mod.rs:307:21
  11: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/x11/mod.rs:385:9
  12: winit::platform_impl::platform::EventLoop<T>::run
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:662:56
  13: winit::event_loop::EventLoop<T>::run
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/event_loop.rs:154:9
  14: slscenetester::displaystate
             at /home/john/projects/sl/SL-test-viewer/slscenetester/src/main.rs:503:5
  15: slscenetester::main
             at /home/john/projects/sl/SL-test-viewer/slscenetester/src/main.rs:890:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by cwfitzgerald** [comment]
The warnings/errors are annoying, but they're actually all expected and benign.

First is that wgpu tries to enable the validation layers in debug mode, but if you don't have them installed it'll show that error.

Mailbox -> Fifo fallback just means it's using a more-widely supported mode of vsync.

The two Naga errors are because glslc generates spirv that touches a builtin variable that I don't use, and webgpu doesn't support. This has been made a soft error because it how common it is.

The panic is a mismatch in what wgpu expects vs the uploaded texture when uploading a cubemap. What size/format/mipmap setting is the cubemap you're uploading?

**Comment by John-Nagle** [comment]
That makes sense. Trying to figure out what call caused that.

**Comment by John-Nagle** [comment]
The crash was caused by the skybox loading. That code was copied from scene-tester, but needed to be updated for the new Rend3. I can now load all my geometry with the default grey texture. The first actual texture load failed with the message below. Probably because I used Rgba8Uint when converting to Rend3 1.0. I will try to figure out the new rules.

```
04:11:35 [ERROR] wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `D2 texture bg`
    texture binding 0 expects sample type = Float { filterable: true }, but given a view with format = Rgba8Uint


thread 'main' panicked at 'Handling wgpu errors as fatal by default', /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/backend/direct.rs:2159:5
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:541:12
   1: wgpu::backend::direct::default_error_handler
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/backend/direct.rs:2159:5
   2: core::ops::function::Fn::call
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:70:5
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1586:9
   4: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/backend/direct.rs:2146:9
   5: wgpu::backend::direct::Context::handle_error
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/backend/direct.rs:166:9
   6: <wgpu::backend::direct::Context as wgpu::Context>::device_create_bind_group
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/backend/direct.rs:1127:13
   7: wgpu::Device::create_bind_group
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/lib.rs:1685:17
   8: rend3::resources::texture::create_bind_group
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/rend3-0.1.0/src/resources/texture.rs:212:14
   9: rend3::resources::texture::TextureManager::ready
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/rend3-0.1.0/src/resources/texture.rs:123:44
  10: <rend3_pbr::PbrRenderRoutine as rend3::routine::RenderRoutine>::render
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/rend3-pbr-0.1.0/src/lib.rs:143:33
  11: rend3::renderer::render::render_loop
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/rend3-0.1.0/src/renderer/render.rs:260:5
  12: rend3::renderer::Renderer::render
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/rend3-0.1.0/src/renderer/mod.rs:219:9
  13: slscenetester::displaystate::{{closure}}
             at /home/john/projects/sl/SL-test-viewer/slscenetester/src/main.rs:705:40
  14: winit::platform_impl::platform::sticky_exit_callback
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:746:5
  15: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/x11/mod.rs:307:21
  16: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/x11/mod.rs:385:9
  17: winit::platform_impl::platform::EventLoop<T>::run
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:662:56
  18: winit::event_loop::EventLoop<T>::run
             at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/event_loop.rs:154:9
  19: slscenetester::displaystate
             at /home/john/projects/sl/SL-test-viewer/slscenetester/src/main.rs:514:5
  20: slscenetester::main
             at /home/john/projects/sl/SL-test-viewer/slscenetester/src/main.rs:900:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Current texture creation code looks like this:

```
    let mips = 1;       // ***TEMP** no mipmapping
    let texture = Texture {
        label: Some(format!("{:?}", uuid_key_range)),
        ////format: match srgb {
        ////    true => dt::TextureFormat::Rgba8Srgb,
        ////    false => dt::TextureFormat::Rgba8Linear,
        ////},
        format: TextureFormat::Rgba8Uint,   // ***NOT SURE ABOUT THIS***
        ////format: TextureFormat::Rgba8Srgb,
        ////width: rgba.width(),
        ////height: rgba.height(),
        size: UVec2::new(rgba.width(), rgba.height()),
        data: rgba.into_raw(),
        //// TODO: automatic mipmapping (#53)
        ////mip_levels: 1,
        mip_count: rend3::types::MipmapCount::Specific(NonZeroU32::new(mips).unwrap()),
        mip_source: rend3::types::MipmapSource::Uploaded,
    };

```

This is probably wrong. Advice?

**Comment by cwfitzgerald** [comment]
Descriptor looks fine outside of the format. I forgot to include a mapping in the changelog. The tldr is that I read all textures as floating point in my shaders. So any float formats the mapping is clear. For integer formats there's the Unorm type qualifier that says it's an integer in memory, but will be converted to a normalized float in the shader. In this case you'd use Rgba8Unorm for linear and Rgba8UnormSrgb. The [TextureFormat](https://docs.rs/wgpu/0.10.1/wgpu/enum.TextureFormat.html) wgpu docs have a lot more information on this (rend3 just typedefs this type). Anything that is "float in shaders" will work.

**Comment by John-Nagle** [comment]
Changed to format: `TextureFormat::Rgba8UnormSrgb,   // per WGPU tutorial` and started to get textures. So now rendering is starting to work again. Lots of minor issues with the conversion. Not too bad.

- The alpha channel in the image is set to 0 for transparent objects, and that now seems to have no effect.
- There is no ambient lighting, and no obvious way to set it. I've been searching the Rend3 code for "ambient" without success.

I have to figure out the new transparency system, etc. Anyway, so far so good.

![firstrend0 1 0viz](https://user-images.githubusercontent.com/942608/133026022-9e2c3ca0-e6e0-47d6-9a8a-82ef61148c04.png)

**Comment by cwfitzgerald** [comment]
Going to close this for now as these issues now have #189
