### ISSUE TITLE
rend3 segfaults when trying to create a `DepthPipeline` for a custom material

### ISSUE THREAD

**Issue by setzer22** [BVE-Reborn/rend3#363]
As discussed on the matrix, here's the reproduction example (sorry for the brevity!) https://github.com/setzer22/rend3_ub_repro

**Comment by setzer22** [comment]
Here's a gdb backtrace:

```
#0  0x00007ffff6d33b12 in ?? () from /usr/lib/libvulkan_radeon.so
#1  0x00007ffff6d675b3 in ?? () from /usr/lib/libvulkan_radeon.so
#2  0x00007ffff6d407ef in ?? () from /usr/lib/libvulkan_radeon.so
#3  0x00007ffff6d43e7a in ?? () from /usr/lib/libvulkan_radeon.so
#4  0x00007ffff6d46f0e in ?? () from /usr/lib/libvulkan_radeon.so
#5  0x00007ffff6d47008 in ?? () from /usr/lib/libvulkan_radeon.so
#6  0x000055555660346a in ash::vk::features::DeviceFnV1_0::create_graphics_pipelines (self=0x5555571e9a58, device=..., 
    pipeline_cache=..., create_info_count=1, p_create_infos=0x7fffffff53a0, p_allocator=0x0, p_pipelines=0x555556dcb2d0)
    at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.34.0+1.2.203/src/vk/features.rs:4275
#7  0x00005555565e73eb in ash::device::Device::create_graphics_pipelines (self=0x5555571e9a50, pipeline_cache=..., 
    create_infos=..., allocation_callbacks=...)
    at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.34.0+1.2.203/src/device.rs:1553
#8  0x00005555564750f2 in wgpu_hal::vulkan::device::{impl#4}::create_render_pipeline (self=0x5555571ccd18, 
    desc=0x7fffffff7b50)
    at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.12.4/src/vulkan/device.rs:1558
#9  0x000055555624f36f in wgpu_core::device::Device<wgpu_hal::vulkan::Api>::create_render_pipeline<wgpu_hal::vulkan::Api, wgpu_core::hub::IdentityManagerFactory> (self=0x5555571ccd18, self_id=..., adapter=0x555556d973c8, desc=0x7fffffff9440, 
    implicit_context=..., hub=0x555556d92d58, token=0x7fffffff8850)
    at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.12.2/src/device/mod.rs:2623
#10 0x000055555605d674 in wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_render_pipeline<wgpu_core::hub::IdentityManagerFactory, wgpu_hal::vulkan::Api> (self=0x555556d92c40, device_id=..., desc=0x7fffffff9440, 
    id_in=..., implicit_pipeline_ids=...)
    at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.12.2/src/device/mod.rs:4415
#11 0x000055555629378a in wgpu::backend::direct::{impl#3}::device_create_render_pipeline (self=0x555556d92c40, 
    device=0x555557180d08, desc=0x7fffffff9a98)
    at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:1303
#12 0x00005555560c30e4 in wgpu::Device::create_render_pipeline (self=0x555557180d00, desc=0x7fffffff9a98)
    at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/lib.rs:1810
#13 0x0000555555f4c9ea in rend3_routine::depth::create_depth_inner (renderer=0x555557209980, 
    samples=rend3_types::SampleCount::One, ty=rend3_routine::depth::DepthPassType::Shadow, unclipped_depth_supported=true, 
    pll=0x7fffffff9fc8, vert=0x7fffffff9f70, frag=0x7fffffff9f90, name=...)


```
