### ISSUE TITLE
Crashes when using Wayland on Ubuntu 22.04 LTS latest

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#515]
Tried latest Rend3 from Trunk on Wayland:

 ```
> ./cube
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost
', /home/john/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:734:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: wgpu::backend::direct::Context::handle_error_fatal
             at /home/john/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:308:9
   3: <wgpu::backend::direct::Context as wgpu::context::Context>::surface_configure
             at /home/john/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:734:13
   4: <T as wgpu::context::DynContext>::surface_configure
             at /home/john/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/context.rs:2056:9
   5: wgpu::Surface::configure
             at /home/john/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/lib.rs:4150:9
   6: rend3::surface::configure_surface
             at /home/john/projects/rend3/rend3/src/surface.rs:15:5
   7: rend3_framework::async_start::{{closure}}::{{closure}}
             at /home/john/projects/rend3/rend3-framework/src/lib.rs:238:9
   8: core::option::Option<T>::map_or
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/option.rs:1133:24
   9: rend3_framework::async_start::{{closure}}
             at /home/john/projects/rend3/rend3-framework/src/lib.rs:233:18
  10: pollster::block_on
             at /home/john/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128:15
  11: rend3_framework::start
             at /home/john/projects/rend3/rend3-framework/src/lib.rs:433:9
  12: rend3_cube_example::main
             at /home/john/projects/rend3/examples/cube/src/lib.rs:201:5
  13: cube::main
             at /home/john/projects/rend3/examples/cube/src/main.rs:2:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
Didn't really expect this to work yet, but Wayland is taking over, and it's time to get ready.
Vulkan config info attached. NVidia 3070 GPU. Ubuntu 22.04 LTS, current.
"vxcube", the basic is-Vulkan-working test, displays a cube. 

Vulkaninfo:
[vulkaninfo.txt](https://github.com/BVE-Reborn/rend3/files/12652355/vulkaninfo.txt)

Blender's view of the graphics situation:
[system-info.txt](https://github.com/BVE-Reborn/rend3/files/12652327/system-info.txt)

**Comment by cwfitzgerald** [comment]
I suspect this is something upstream, definitely not a rend3 issue.
